spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080


cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET, POST, PUT, DELETE
  allowed-headers: Content-Type, Authorization
